### PR TITLE
Update examples for amphp/http-server v0.8

### PR DESCRIPTION
**Pull request by krlv**
Fix for #7:
- update examples and list of dependencies in composer.json
- ~fix test server implementation that is used for `autobahn` tests~

Updated: test server's fix moved to separate issue #8 (and separate PR #9 )

### CODE REVIEW

**Comment by krlv** [comment]
@trowski / @kelunik Could you please review the PR?

Note: Travis' build failed because of Autobahn tests. I'm not familiar with this tool, but it looks like these test cases are failing: https://github.com/crossbario/autobahn-testsuite/blob/master/autobahntestsuite/autobahntestsuite/case/case12_x_x.py#L45 (probably because of default websocket-server configs)

**Comment by krlv** [comment]
Just a kind reminder on this issue. Could you please review/comment the issue? Maybe a suggestion on how to fix Autobahn tests (if they should be fixed at all).

Thanks in advance 🙇

**Comment by PeeHaa** [comment]
Maybe you can split up the autobahn issues to a separate PR / issue so at the very least the updated example can be merged in easily?

**Comment by krlv** [comment]
Thanks for advice @PeeHaa 👍 

I've created a new issue for fixing test server #8 and moved all commits related to it to a separate PR #9 
It will be easier to review it this way.

**Pull request merged**
